[package]
name = "rpc_fib"
version = "1.0.0"
edition = "2021"

[dependencies.amiquip]
version = "0.4.2"
default-features = false

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",
    "fast-rng",
]

[[bin]]
name = "publisher"

[[bin]]
name = "consumer"